# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Slender Poster"
license = "MIT"
licenselink = "https://github.com/obviateio/hugo-slender-poster/blob/master/LICENSE"
description = "A different take on Chunky Poster, a bootstrap 4 based blog theme."
homepage = "https://github.com/obviateio/hugo-slender-poster/"
tags = ["minimal", "minimalist", "blog", "responsive", "syntax highlighting", "multilingual", "minimalist", "light"]
features = ["minimal", "minimalist", "blog", "responsive", "syntax highlighting", "multilingual", "minimalist", "light", "pagination"]
min_version = "0.41"

[author]
  name = "Jon Davis"
  homepage = "https://obviate.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
